<?php

namespace App\Http\Controllers;

use App\Models\GeneratedPerson;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ResetController extends Controller
{
    public function index()
    {
        return view('pages/reset');
    }

    public function reset()
    {
        // Remove all rows generated by the signed-in user in generated_people table
        GeneratedPerson::where('user_id', Auth::id())->delete();

        // Go to same view but with success message
        return view('pages/reset')->with(['success_message' => '<strong>Success!</strong> All user records were deleted.']);
    }
}
